name: CI workflow

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
